#!/bin/bash

if [ "$#" -lt 1 ]
then
    echo "Usage: $0 <filename.java>"
fi

base_dir="$(realpath $(dirname $0))"
app_exe="$base_dir/app/build/install/app/bin/app"
if [ ! -f "$app_exe" ]
then
    echo "Could not find app executable: $app_exe"
    exit 1
fi

java_file="$1"
shift 1
if [ ! -f "$java_file" ]
then
    echo "Could not find file: $java_file"
    exit 1
fi

# Create temp dir, copy solution file to it, compile
tmpdir="$(mktemp -d)"
cp "$java_file" "$tmpdir/Main.java"
cd "$tmpdir"
echo "Compiling..."
javac -encoding utf8 -g Main.java # Fix for compiling Japanese code https://stackoverflow.com/a/14672757/8999671
exitCode="$?"
if [ "$exitCode" -ne 0 ]
then
    exit $exitCode
fi

echo "Analyzing..."
"$app_exe" Main main $@
exitCode="$?"
rm -r $tmpdir

exit $exitCode
